// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAul7MbWIB0-T-3_XMA5QtBs87fltwNujI',
    appId: '1:250496639739:web:66fd07b33744df9f84865e',
    messagingSenderId: '250496639739',
    projectId: 'todoapp-978b3',
    authDomain: 'todoapp-978b3.firebaseapp.com',
    storageBucket: 'todoapp-978b3.firebasestorage.app',
    measurementId: 'G-7XBDS1ZQW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwo4gSXp5n9k6npezhrSNreuGxG_VIhy4',
    appId: '1:250496639739:android:43ff503b12a3ee0084865e',
    messagingSenderId: '250496639739',
    projectId: 'todoapp-978b3',
    storageBucket: 'todoapp-978b3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAul7MbWIB0-T-3_XMA5QtBs87fltwNujI',
    appId: '1:250496639739:web:5594289d190e5e4984865e',
    messagingSenderId: '250496639739',
    projectId: 'todoapp-978b3',
    authDomain: 'todoapp-978b3.firebaseapp.com',
    storageBucket: 'todoapp-978b3.firebasestorage.app',
    measurementId: 'G-RPEFRGFC45',
  );

}